### ISSUE TITLE
adding sHermes

### ISSUE THREAD

**Issue by otr4v3z** [Hermes-defi/hermes-swap#12]
sHERMES is a contract that allows HERMES deposits and receives stablecoins sent by MoneyMaker's daily harvests. Users deposit HERMES and receive a share of what has been sent by MoneyMaker based on their participation of
the total deposited HERMES. It is similar to a MasterChef, but we allow for claiming of different reward tokens

**Comment by AustinHDev** [comment]
sHRMS can now be found at https://github.com/Hermes-defi/hermes-swap/blob/main/contracts/StableHermesStaking.sol
