### ISSUE TITLE
Partner Reward Distribution Error

### ISSUE THREAD

**Issue by otr4v3z** [Hermes-defi/hermes-swap#4]
Discrepancy when calculating rewards token due added deflationary token prevention code. received less partner token than expected.
``` .sol
        if (_amount > 0) {
            uint256 balanceBefore = pool.lpToken.balanceOf(address(this));
            pool.lpToken.safeTransferFrom(
                address(msg.sender),
                address(this),
                _amount
            );
            _amount = pool.lpToken.balanceOf(address(this)).sub(balanceBefore);
        }
```

**Comment by ghost** [comment]
Mad changes and comments on this branch: https://github.com/Hermes-defi/hermes-swap/tree/5-reward-distribution

**Comment by AustinHDev** [comment]
This issue has been resolved as part of our Certik Audit
